#!/usr/bin/env bash
clang-format -i src/*

# Check if any files in the linted directories were modified
if git diff --name-only | grep -E '^(src/)' | grep -q .; then
  echo "Linting required edits. Files were modified."
  exit 1
fi
