name: main

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Make scripts executable
        run: chmod +x scripts/lint

      - name: Check linter
        run: ./scripts/lint

  build:
    runs-on: ubuntu-latest
    needs: [check]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Make scripts executable
      run: |
        ls -l
        chmod +x scripts/raylib scripts/build

    - name: Install emsdk
      run: source scripts/emsdk

    - name: Compile raylib
      run: ./scripts/raylib

    - name: Build the game
      run: ./scripts/build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5.0.0
      with:
        name: github-pages
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5
